database: Launcher.java ProjectLauncher.java Dataloader.java AdminView.java Signup.java GUI.java Manager.java
	javac Launcher.java ProjectLauncher.java Dataloader.java AdminView.java Signup.java GUI.java Manager.java
	java ProjectLauncher
clean: 
	rm *.class