database: Launcher.java ProjectLauncher.java Dataloader.java AdminView.java Signup.java GUI.java
	javac Launcher.java ProjectLauncher.java Dataloader.java AdminView.java Signup.java GUI.java
	java ProjectLauncher

setup:
	export CLASSPATH=./:./ojdbc14.jar
# 	export CLASSPATH=Users/saikathika/document/Databases-dddebd2b004744a863477f050542f740b9a9337dojdbc14.jar
clean: 
	rm *.class